sftp:
  config:
    remoteDirectory: /upload/in/statements/
    localDirectory: tmp/
    host: sftp
    user: tester
    password: password
    port: 22
      
spring:
  kafka:
    producer:
      client-id: ecs-bank-statement-producer
      bootstrap-servers: broker:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://schema-registry:8081

s3:
  config:
    url: http://localstack:4566
    region: south-east-1
    access-key-id: test
    secret-key-id: test

application:
  config:
    reader:
      integration-code: ecs
      process: STATEMENTS
      validation-required: true
      topic: Transformation1
